
cities = ["Mumbai", "Delhi", "Bangalore", "Hyderabad", 
        "Ahmedabad", "Chennai", "Kolkata", "Surat", 
        "Pune", "Jaipur", "Lucknow", "Nagpur", 
        "Visakhapatnam", "Indore", "Thane", "Bhopal", 
        "Pimpri-Chinchwad",	"Patna", "Vadodara", 
        "Ghaziabad", "Ludhiana", "Coimbatore", 
        "Agra", "Madurai", "Nashik", "Faridabad", 
        "Meerut", "Rajkot", "Kalyan-Dombivali", 
        "Varanasi", "Srinagar", "Aurangabad", 
        "Dhanbad", "Amritsar", "Navi Mumbai", 
        "Allahabad", "Ranchi", "Jabalpur", "Gwalior", 
        "Vijayawada", "Jodhpur", "Malegaon", 
        "Tirunelveli", "Ambattur", "Belgaum", 
        "Mangalore"]